[package]
name = "nfdfix"
version = "0.3.0"
edition = "2024"
description = "Fix NFD-normalized filenames"
authors = ["jhyeok1023"]
license = "BSD-3-Clause"
repository = "https://github.com/jhyeok1023/nfdfix"

[dependencies]
unicode-normalization = "0.1.25"
walkdir = "2.5.0"
clap = { version = "4.5.60", features = ["derive"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = true
codegen-units = 1
